kadena-io/pact-5

- pact-tests/pact-tests/caps.repl
- pact/Pact/Core/IR/Eval/CEK.hs
While working on the gas and a direct-style evaluator, while translating the code from CEK to the direct evaluator, I noticed that we somehow slipped by hard-coding `PopCapInvoke` during `CapPopC`. It causes managed capabilities that are composed with other managed capabilities to be incorrectly popped off the cap stack.
This pr simply passes `cappop` and adds a regression for the behavior
PR checklist:
> fix multi-nested managed cap composition

- pact/Pact/Core/IR/Eval/CoreBuiltin.hs
The existing `repl` tests checking that `describe-table` only happens at top-level pass by semi-coincidence: the table isn't considered a pact value, so that check errors out. This PR adds an explicit check that `describe-table` is only called at top-level, instead of relying on what constitutes a pact value.
PR checklist:
> Explicitly enforce `describe-table` top-levelness

- pact-tests/pact-tests/pact-version.repl
- pact-tests/pact-tests/toplevel.repl
- pact-tng.cabal
- pact/Pact/Core/Builtin.hs
- pact/Pact/Core/Errors.hs
- pact/Pact/Core/Gas/TableGasModel.hs
- pact/Pact/Core/IR/Desugar.hs
- pact/Pact/Core/IR/Eval/CoreBuiltin.hs
- pact/Pact/Core/Repl/Runtime/ReplBuiltin.hs
- pact/Pact/Core/Serialise/CBOR_V1.hs
This PR adds the `pact-version` and `enforce-pact-version` builtin.
closes #79 
PR checklist:
---
- https://app.asana.com/0/0/1206417680988237
> add `pact-version` and `enforce-pact-version` builtin

- pact-tests/pact-tests/ops.repl
- pact/Pact/Core/IR/Eval/CoreBuiltin.hs
- pact/Pact/Core/PactValue.hs
See: https://app.asana.com/0/1204069832833999/1206459570889561
Closes #86 
Closes #87 
This PR fixes the following:
Take/drop on strings behaving incorrectly due to incorrect bounds checks. The following is output from the repl after the fixes in this PR.
```
pact>(drop -4 "ABC")
""
pact>(drop -5 "ABC")
""
```
Object pretty printing
```
pact>(format "{}" [{'a:3}])
"{"a":3}"
pact>(print {'a:3})
{"a":3}
()
```
PR checklist:
> Fix take/drop and Obj pretty printing

- pact-tests/pact-tests/caps.repl
- pact-tests/pact-tests/coin-v1.repl
- pact-tests/pact-tests/coin-v5.repl
- pact-tests/pact-tests/db.repl
- pact-tests/pact-tests/keysets.repl
- pact/Pact/Core/IR/Eval/CEK.hs
- pact/Pact/Core/Repl/Runtime/ReplBuiltin.hs
closes #91 
With this PR, we check if our expected error matches the raised one.
```
pact>(defun make-error () (enforce false "Error Foo"))
Loaded defun make-error
pact>(expect-failure "Should raise foo" "Error Bar" (make-error))
"FAILURE: Should raise foo: expected error message 'Error Bar', got 'Error Foo'"
pact>(expect-failure "Should raise foo" "Error Foo" (make-error))
"Expect failure: Success: Should raise foo"
```
PR checklist:
---
- https://app.asana.com/0/0/1206473309875658
> Expect-failure error mesage check

- gasmodel/Pact/Core/GasModel/Utils.hs
- pact-tests/Pact/Core/Gen/Serialise.hs
- pact-tests/pact-tests/leftpad.repl
- pact-tests/pact-tests/modulehash.repl
- pact-tests/pact-tests/repl-toplevels.repl
- pact-tests/pact-tests/yield.repl
- pact/Pact/Core/Compile.hs
- pact/Pact/Core/IR/ConstEval.hs
- pact/Pact/Core/IR/Desugar.hs
- pact/Pact/Core/IR/Eval/CEK.hs
- pact/Pact/Core/IR/ModuleHashing.hs
- pact/Pact/Core/IR/Term.hs
- pact/Pact/Core/PactValue.hs
- pact/Pact/Core/Repl.hs
- pact/Pact/Core/Repl/Compile.hs
- pact/Pact/Core/Serialise/CBOR_V1.hs
- pact/Pact/Core/SizeOf.hs
- pact/Pact/Core/Type.hs
In this pr, the following in a repl script
```
(module m g
(defcap g ()
@doc "bloop"
true)
(defun dfun-example:integer (a:integer)
@doc "these are the defun docs"
(+ a 1)
)
(defcap dcap-example:integer (a:integer)
@doc "these are the defcap docs"
(+ a 1)
)
(defpact dpact-example:integer (a:integer)
@doc "these are the defpact docs"
(step 1)
)
(defconst dconst-example:integer 1
@doc "this is the defconst example"
)
(defschema schema-example
@doc "this is the schema doc"
a:integer)
(deftable tbl-example:{schema-example}
@doc "this is the table docs"
)
)
dconst-example
dfun-example
dcap-example
dpact-example
tbl-example
```
Produces
```
Loaded module m, hash LmLumnFm1auzfNPEMEbK8Q0FufFJ2sMqTGsuq2wfuqw
(defconst dconst-example:integer 1)
Docs:
this is the defconst example
(defun …
```
> Fix doc pretty printing

- pact-tests/pact-tests/fqns.repl
- pact-tests/pact-tests/strtoint.repl
- pact/Pact/Core/IR/Eval/CoreBuiltin.hs
- pact/Pact/Core/IR/Term.hs
Closes #98
Closes #97 
This PR Fixes the behavior around invalid inputs in the string->int and int->string conversion functions.
```
pact>(expect-failure "str-to-int on negative number" (str-to-int "-123"))
"Expect failure: Success: str-to-int on negative number"
pact>(expect-failure "int-to-str on negative numbers" (int-to-str 10 -36))
"Expect failure: Success: int-to-str on negative numbers"
```
As well as fixes the regression in #98. Turns out that it was just our `Plated` instance that was traversing `BuiltinForm`s incorrectly. After the fix, we can expect the example in the issue to work, and i've also added it as a regression
PR checklist:
> Patch (int->string,str->int) and buggy plated instance

- pact-tests/pact-tests/pact-version.repl
This PR adds a missing test case, which was added in prod: https://github.com/kadena-io/pact/pull/1334 
The check against `pact-version`.
PR checklist:
> `enforce-pact-version` test case

- cabal.project
- crypto/Pact/Core/Crypto/Pairing.hs
- pact-tng.cabal
- pact/Pact/Core/IR/Eval/CoreBuiltin.hs
To build/run with profiling, pass `--flags="-with-crypto"` to `cabal`. This disables all `poly`-related stuff (namely, ZK and poseidon hash), but that should still be good enough to build the core with profiling and get meaningful performance data.
PR checklist:
> Profiling build support

- .github/workflows/nix.yml
- flake.lock
- flake.nix
This PR adds releasing binary artefacts once they pass CI as `development-latest`. The general idea is to ship new versions of the LSP server via the VSCode plugin.
PR checklist:
> Publish binary as development-latest

- pact-tests/pact-tests/identity.repl
- pact/Pact/Core/Builtin.hs
- pact/Pact/Core/Gas/TableGasModel.hs
- pact/Pact/Core/IR/Desugar.hs
- pact/Pact/Core/IR/Eval/CoreBuiltin.hs
- pact/Pact/Core/Serialise/CBOR_V1.hs
In this PR we add a dedicated builtin for the `identity` function. So-far, it was desugared directly into a lambda. This prevented us from displaying docs from the LSP.
PR checklist:
---
- https://app.asana.com/0/0/1207151514407085
> add identity builtin to support LSP

- gasmodel/Pact/Core/GasModel/InterpreterGas.hs
- gasmodel/Pact/Core/GasModel/Utils.hs
- pact-tests/Pact/Core/Test/ReplTests.hs
- pact-tests/pact-tests/modref-recursion.repl
- pact-tests/pact-tests/repl-toplevels.repl
- pact-tng.cabal
- pact/Pact/Core/Environment/Types.hs
- pact/Pact/Core/Environment/Utils.hs
- pact/Pact/Core/Errors.hs
- pact/Pact/Core/IR/Eval/CEK.hs
- pact/Pact/Core/IR/Eval/CoreBuiltin.hs
- pact/Pact/Core/IR/Eval/Runtime/Types.hs
- pact/Pact/Core/IR/Eval/Runtime/Utils.hs
- pact/Pact/Core/IR/Term.hs
- pact/Pact/Core/Names.hs
- pact/Pact/Core/PactValue.hs
- pact/Pact/Core/Pretty.hs
- pact/Pact/Core/Repl/Runtime/ReplBuiltin.hs
- pact/Pact/Core/Repl/Utils.hs
- pact/Pact/Core/StackFrame.hs
This PR improves the state of error messages in core, as well as adds a runtime recursion check for module references.
Given this repl file:
```
(module caller g
(defcap g () true)
(defun caller ()
(caller1)
)
(defun caller1 ()
(caller2 31)
)
(defun caller2 (a:integer)
(caller3 31 "bob`")
)
(defun caller3 (a:integer arg:string)
(enforce false "whoopsie!")
)
)
(caller)
```
Pre-this PR, the following is a repl snippet of the error emitted by loading the file:
```
pact>(load "example.repl" true)
"Loading example.repl..."
Loaded module caller, hash Z9GxDb9xe8joF3x1SfeqbMuN9RrSSekRm5N2TBTJ5zI
example.repl:18:4: Program encountered an unhandled raised error: whoopsie!
18 |     (enforce false "whoopsie!")
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Post-this, the error improves to
```
pact>(load …
```
> Improve callstack errors, check for recursion.

- cbits/musl/endian.h
This Pr removes the annoying compiler warning regarding the `endian.h` file.
PR checklist:
> remove compiler warnings

- pact-tng.cabal
This PR reduces the dependencies for the chainweb integration.
PR checklist:
> remove unused dependencies

- .github/pull_request_template.md
- pact-tests/constructor-tag-goldens/LexerError.golden
- pact-tests/pact-tests/disableRTC.repl
- pact-tests/pact-tests/side-effects.repl
- pact/Pact/Core/Environment/Types.hs
- pact/Pact/Core/Errors.hs
- pact/Pact/Core/IR/Eval/CEK.hs
- pact/Pact/Core/IR/Eval/Direct/Evaluator.hs
- pact/Pact/Core/IR/Eval/Direct/ReplBuiltin.hs
- pact/Pact/Core/IR/Eval/Runtime/Utils.hs
- pact/Pact/Core/IR/Term.hs
- pact/Pact/Core/Repl/Runtime/ReplBuiltin.hs
- pact/Pact/Core/Syntax/LexUtils.hs
- pact/Pact/Core/Syntax/Lexer.x
- pact/Pact/Core/Syntax/ParseTree.hs
Rename progn to do
```
pact>(do 1 2 3)
3
```
Factor out common code between CEK/Direct
PR checklist:
> Core: Fix return RTC flag, Events Disable flag

- pact-tng.cabal
- pact/Pact/Core/Errors.hs
- pact/Pact/Core/IR/Eval/Direct/ReplBuiltin.hs
- pact/Pact/Core/Repl/Runtime/ReplBuiltin.hs
- pact/Pact/Core/Version.hs
- repl/Main.hs
This PR simply creates a static version of the autogenerated `PackageInfo_pact_tng`, while we fix our CI.
> fix pact version for CI

- gasmodel/Pact/Core/GasModel/ContractBench.hs
- gasmodel/Pact/Core/GasModel/Serialization.hs
- pact-tests/Pact/Core/Test/GasGolden.hs
- pact-tests/pact-tests/modref-recursion.repl
- pact-tng.cabal
- pact/Pact/Core/Builtin.hs
- pact/Pact/Core/Compile.hs
- pact/Pact/Core/Environment/Types.hs
- pact/Pact/Core/Evaluate.hs
- pact/Pact/Core/Gas.hs
- pact/Pact/Core/Gas/TableGasModel.hs
- pact/Pact/Core/Gas/Types.hs
- pact/Pact/Core/Gas/Utils.hs
- pact/Pact/Core/IR/Eval/CoreBuiltin.hs
- pact/Pact/Core/IR/Eval/Direct/Evaluator.hs
- pact/Pact/Core/IR/Eval/Direct/ReplBuiltin.hs
- pact/Pact/Core/IR/Eval/Runtime/Utils.hs
- pact/Pact/Core/Persistence/Types.hs
- pact/Pact/Core/Persistence/Utils.hs
- pact/Pact/Core/Repl/Runtime/ReplBuiltin.hs
- pact/Pact/Core/Repl/Utils.hs
- pact/Pact/Core/SizeOf.hs
- profile-tx/ProfileTx.hs
This PR monomorphizes our Gas model charging to always use our gas table. There's about a 10% speed increase from this change.
Numbers pre-pr:
```
benchmarking Pact Core Benchmarks/Pure Code/Factorial 1000
time                 216.1 μs   (215.8 μs .. 216.7 μs)
1.000 R²   (1.000 R² .. 1.000 R²)
mean                 216.0 μs   (215.8 μs .. 216.8 μs)
std dev              1.236 μs   (327.0 ns .. 2.522 μs)
benchmarking Pact Core Benchmarks/Coin Transfer/InterpretOnly(transfer) from SenderA to SenderB using: CEK
time                 76.84 μs   (76.76 μs .. 76.92 μs)
1.000 R²   (1.000 R² .. 1.000 R²)
mean                 76.95 μs   (76.91 μs .. 77.00 μs)
std dev              106.9 ns   (83.52 ns .. 159.7 ns)
benchmarking Pact Core Benchmarks/Coin Transfer/InterpretOnly(transfer) from SenderA to …
```
> Core: Improve Gasmodel charging, monomorphize to gas table.

- gasmodel/Pact/Core/GasModel/Utils.hs
- pact-request-api/Pact/Core/Command/Types.hs
- pact/Pact/Core/Compile.hs
- pact/Pact/Core/Evaluate.hs
Based on #189.
`MsgData` doesn't need `mdStep` anymore, it isn't used. `initMsgData` is just a footgun for me. 
`_erInput` makes the interface of `Evaluate` more annoying to use and doesn't seem to be needed.
`Pact.Core.Evaluate.ContMsg` was renamed to `Cont`. Not to be confused with `Pact.Core.Command.RPC.ContMsg`, which is public API.
PR checklist:
> Bundle of changes from integration work

- .github/workflows/cabal.yml
The freshly triggered CI should fail for all builds except `cabal 3.6.6`.
PR checklist:
> Add cabal build via GH actions

- pact/Pact/Core/Errors.hs
- repl/Main.hs
output:
```
The Pact Smart Contract Language Interpreter
Usage: pact [(-v|--version) | (-b|--builtins) | --lsp | (-a|--apireq REQ_YAML) 
[-l|--local] |
(-u|--unsigned REQ_YAML) | [-r|--findscript] [-t|--trace] FILE | 
--explain-error-code ERROR_CODE]
Available options:
-h,--help                Show this help text
-v,--version             Display version
-b,--builtins            List builtins
--lsp                    Start Language Server
-a,--apireq REQ_YAML     Format API request JSON using REQ_YAML file
-l,--local               Format for /local endpoint
-u,--unsigned REQ_YAML   Format unsigned API request JSON using REQ_YAML file
-r,--findscript          For .pact files, attempts to locate a .repl file to
execute.
-t,--trace               Show trace output
FILE                     File …
```
> add `--explain-error-code ERROR_CODE flag` to the repl

- test-utils/Pact/Core/PactDbRegression.hs
Stops accessing the database outside of transactions and stops leaving a dangling transaction at the end. chainweb now checks for these conditions.
> fix PactDbRegression transactionally

- pact/Pact/Core/Environment/Types.hs
- pact/Pact/Core/Evaluate.hs
- pact/Pact/Core/Persistence/SQLite.hs
- pact/Pact/Core/Repl.hs
- tools/LegacyPactDbCheck.hs
Fix our external facing `Evaluate` api to properly rollback on calls to the `evalExec` family of functions.
The testing of this PR is done within chainweb.
PR checklist:
> Fix internal evaluate API to catch unknown exceptions

- pact/Pact/Core/Errors.hs
- pact/Pact/Core/Persistence/MockPersistence.hs
> Amend NoTxInCommit error to more general NotInTx error

- CHANGELOG.md
As mentioned in #212  by @emilypi , seeding the changelog from pact < 5.
PR checklist:
> seeding changelog from pact < 5

- pact-request-api/Pact/Core/Command/Client.hs
- pact-request-api/Pact/Core/Command/Types.hs
- pact-tests/Pact/Core/Test/SignatureSchemeTests.hs
- pact-tng.cabal
- pact/Pact/Core/Capabilities.hs
- pact/Pact/Core/Evaluate.hs
- pact/Pact/Core/PactValue.hs
- pact/Pact/Core/Signer.hs
- pact/Pact/Core/StableEncoding.hs
This PR moves `Signer` into its own module, as it isn't really used outside of the chainweb and request API.
Moreover: I am adding a `SigCapability` newtype, that essentially has a fixed json codec for the sake of both chainweb, as well as testing.
The changes here are mostly a refactoring, so it's covered by previous tests for signers. That said: in fixing the codec of `ModuleGuard`, I realize we definitely need a golden test for stable encoding. This will be done by @rsoeldner 
PR checklist:
Doesn't impact perf
> Fix captoken codec, add SigCapability, move Signer to its own module

- gasmodel/Pact/Core/GasModel/ContractBench.hs
- pact-lsp/Pact/Core/LanguageServer.hs
- pact-tests/Pact/Core/Test/GasGolden.hs
- pact-tests/Pact/Core/Test/ReplTests.hs
- pact-tests/Pact/Core/Test/StaticErrorTests.hs
- pact/Pact/Core/Environment/Types.hs
- pact/Pact/Core/Evaluate.hs
- pact/Pact/Core/IR/Eval/CEK.hs
- pact/Pact/Core/IR/Eval/CoreBuiltin.hs
- pact/Pact/Core/IR/Eval/Direct/Evaluator.hs
- pact/Pact/Core/IR/Eval/Runtime/Types.hs
- pact/Pact/Core/IR/Eval/Runtime/Utils.hs
- pact/Pact/Core/Info.hs
- pact/Pact/Core/Names.hs
- pact/Pact/Core/Repl.hs
- pact/Pact/Core/Repl/Compile.hs
- pact/Pact/Core/Repl/Utils.hs
- pact/Pact/Core/Syntax/Parser.y
- profile-tx/ProfileTx.hs
This PR reintroduces runtime warnings, being optionally togged on or off, as well as a new warning whenever a module reference is used.
```
pact>(module m g (defcap g () true) (defun some-guard () (create-module-guard "boop")))
Loaded module m, hash OE27e8Ms6lBjXMdlolQQ9NyKJNc_EKEbsa_RjZGkOtY
pact>(some-guard)
Warning: Using deprecated native create-module-guard: Module guards have been deprecated and will be removed in a future release, please switch to capability guards
ModuleGuard {module: m,name: boop}
pact>(enforce-guard (some-guard))
Warning: Using deprecated native create-module-guard: Module guards have been deprecated and will be removed in a future release, please switch to capability guards
Warning: Module guard enforce detected. Module guards are known to be unsafe, and will …
```
> Add warnings to Repl

- pact-request-api/Pact/Core/Command/Types.hs
- pact-tests/Pact/Core/Test/JSONRoundtripTests.hs
- pact/Pact/Core/Errors.hs
- pact/Pact/Core/Hash.hs
- pact/Pact/Core/Info.hs
- pact/Pact/Core/StableEncoding.hs
- test-utils/Pact/Core/Gen.hs
PR checklist:
```
JSON roundtrips for StableEncoding: "PactEvent PactValue":                                                          OK (0.02s)
✓ <interactive> passed 100 tests.
```
N/A
> Integration: Fix PactEvent Codec, add LegacyPactError and Compat types

- pact-tests/pact-tests/db.repl
- pact/Pact/Core/Persistence/SQLite.hs
The following test, prior to this PR, fails on the sqlite pact db (but works fine for in-memory):
```
(begin-tx)
(module m g (defcap g () true)
(defschema sc a:integer b:integer)
(deftable tbl:{sc})
(defun add-elem(a:integer k:string)
(write tbl k {"a":a, "b":a})
)
(defun update-elem(a:integer k:string)
(update tbl k {"a":a})
)
(defun all-elems()
(fold-db tbl (lambda (x y) true) (lambda (k o) {"key":k, "value":o}))
)
)
(create-table tbl)
(commit-tx)
; Add two entries
(begin-tx)
(m.add-elem 1 "jose")
(m.add-elem 1 "robert")
(commit-tx)
(begin-tx)
(m.update-elem 2 "jose")
(m.update-elem 3 "robert")
(commit-tx)
(begin-tx)
(expect "All-elems return distinct objects"
[ {"key": "jose","value": {"a": 2,"b": 1}}
, {"key": "robert","value": {"a": 3,"b": 1}} ]
(m.all-elems))
(commit-tx)
```
This PR …
> Bugfix: Fix sqlite pact db keys implementation, add regression

- docs/builtins/Database/describe-keyset.md
Fixes wrong heading for the `Arguments`, `Return values`, and `Examples` subsections in the `describe-keyset.md` documentation.
The wrong markup heading (currently `##`, it should be`###`) is being used causing them to appear in the right side content menu at `Reference/Functions/Database` ([docs page](https://docs.kadena.io/reference/functions/database)).
PR checklist:
> Fixing heading for sub-sections

- pact-tests/Pact/Core/Test/DocsTests.hs
- pact-tests/Pact/Core/Test/LexerParserTests.hs
- pact/Pact/Core/Builtin.hs
- pact/Pact/Core/Compile.hs
- pact/Pact/Core/Debug.hs
- pact/Pact/Core/Environment/Types.hs
- pact/Pact/Core/Guards.hs
- pact/Pact/Core/IR/Desugar.hs
- pact/Pact/Core/IR/Eval/Direct/ReplBuiltin.hs
- pact/Pact/Core/Info.hs
- pact/Pact/Core/Names.hs
- pact/Pact/Core/Repl.hs
- pact/Pact/Core/Repl/Runtime/ReplBuiltin.hs
- pact/Pact/Core/Repl/UserDocs.hs
- pact/Pact/Core/Repl/Utils.hs
- pact/Pact/Core/Syntax/LexUtils.hs
- pact/Pact/Core/Syntax/Lexer.x
- pact/Pact/Core/Syntax/ParseTree.hs
- pact/Pact/Core/Syntax/Parser.y
- test-utils/Pact/Core/Gen.hs
Contained in this PR are:
- Fixes to span infos for several parser productions (They were not being combined properly, thanks Hedgehog!)
- Fixes to pretty printing in the parse tree (Pretty printing the parse tree will now always produce a parseable representation of the tree. Note: It does not keep documentation intact. We would need a parse tree that does not clobber doc nodes for that. That may come with a pact formatter)
- A slicing function for source locations for toplevel productions for chainweb's use
- Tests for all of the above
- `:debug x` flags are now removed in the repl. Instead replaced by the function `(env-set-debug-flag <flag>)`. Documentation will be in a followup PR (cc @lsgunnlsgunn )
```
pact>(env-set-debug-flag "all")
set debug flags to [lexer, parser, desugar]
() …
```
> Integration + LSP: Improve line loc info in lexer/parser, add test for roundtripping behavior

- .github/workflows/nix.yml
- .github/workflows/release-manual.yml
It resolves the writable permissions issue for the tarball and removes the Nix path from the bundled files, creating a flat directory structure like `/bin` instead of `/nix/store/<nix-stuff>/bin`. This approach follows the conventional method for distributing tarballs.
> fix tarball file permissions to allow  write access for tarball extractor

- .github/workflows/applications.yml
This runs a build of master when a PR is opened in addition to the PR branch being built.  It's not needed and is confusing in the view of the PR builds.
PR checklist:
> remove   pull_request_target trigger

- pact-tests/pact-tests/ops.repl
- pact/Pact/Core/Trans/MPFR.hs
PR checklist:
- Added case to `ops.repl`
> Add NaN and Inf checking to MPFR functions

- pact/Pact/Core/Literal.hs
- pact/Pact/Core/PactValue.hs
- pact/Pact/Core/Pretty.hs
- pact/Pact/Core/StackFrame.hs
While working on separate PRs, I noticed that it is incredibly annoying to sometimes fail with large callstacks, so I've fixed this.
Take this repl file function that simply fails with a callstack:
```pact
(defun fails-with-args (a b c k)
(enforce false "boom")
)
(fails-with-args "a1u23123uh123uh123uh123uh123uh123123" (^ 2 10) 20 (enumerate 1 100))
```
Before this PR, this fails with:
```
Loaded repl defun fails-with-args
scratch/kek.repl:23:2: boom
23 |   (enforce false "boom")
|   ^^^^^^^^^^^^^^^^^^^^^^
at (#repl.fails-with-args "a1u23123uh123uh123uh123uh123uh123123" 1024 20 [ 1
, 2
, 3
, 4
, 5
, 6
, 7
, 8
, 9
...
```
(I cut the output, it goes from 1 to 100)
After this PR:
```
Loaded repl defun fails-with-args
scratch/kek.repl:23:2: boom
23 |   (enforce false "boom")
| …
```
> Improve repl stack frame pretty printing

- pact-tests/pact-tests/hash.repl
- pact/Pact/Core/StableEncoding.hs
This PR fixes the ordering for `StableEncoding` outputs for `PactValue` objects, and adds a simple regression `(hash (chain-data))`, which passes in both prod and pact-5
PR checklist:
N/A
> Integration: Fix Hash ordering from StableEncoding

- pact/Pact/Core/Evaluate.hs
- pact/Pact/Core/Serialise/LegacyPact.hs
Small PR. Changing `Expr Info` to `Expr SpanInfo` is a pretty trivial change which makes all APIs into pact from pactservice consistent.
PR checklist:
> Make evalGasPayerCap have the same Expr type as evalExecTerm

- pact-tests/gas-goldens/builtinGas.golden
- pact/Pact/Core/Evaluate.hs
- pact/Pact/Core/Gas/TableGasModel.hs
- pact/Pact/Core/Gas/Types.hs
- pact/Pact/Core/IR/Eval/CEK/CoreBuiltin.hs
- pact/Pact/Core/IR/Eval/Direct/CoreBuiltin.hs
- pact/Pact/Core/IR/Eval/Direct/Evaluator.hs
- pact/Pact/Core/IR/Eval/Runtime/Utils.hs
- pact/Pact/Core/IR/ModuleHashing.hs
- pact/Pact/Core/PactValue.hs
See also: pact-team-internal on asana.
PR checklist:
> Unify gas charging for all Blake2b Hashes

- docs/builtins/Capabilities/compose-capability.md
- docs/builtins/Capabilities/emit-event.md
- docs/builtins/Capabilities/install-capability.md
- docs/builtins/Capabilities/require-capability.md
- docs/builtins/Capabilities/with-capability.md
I did a small category to test if it will work.
PR checklist:
> Modify format for importing into Docusaurus

- pact-repl/Pact/Core/IR/Eval/Direct/CoreBuiltin.hs
- pact/Pact/Core/IR/Eval/CEK/CoreBuiltin.hs
- pact/Pact/Core/Serialise/LegacyPact.hs
> Fix with-read desugaring to use pattern guard

- docs/builtins/Capabilities/compose-capability.md
- docs/builtins/Capabilities/emit-event.md
- docs/builtins/Capabilities/install-capability.md
- docs/builtins/Capabilities/require-capability.md
- docs/builtins/Capabilities/with-capability.md
Reverts kadena-io/pact-5#279
Circled back with Amir this week and think we have a better solution. We are going to ry a different approach in the transfer script so that the change needed for NextGen docs doesn't impact the formatting and import for the current site until we are ready to transition to the new site.
> Revert "Modify format for importing into Docusaurus"

- pact-repl/Pact/Core/IR/Eval/Direct/Evaluator.hs
- pact-tests/pact-tests/caps.repl
- pact-tests/pact-tests/coin-v5.repl
- pact/Pact/Core/IR/Eval/CEK/Evaluator.hs
This PR makes `install-capability` check whether a capability is provided in the msg sigs before even trying to install it.
PR checklist:
```pact
"Setting transaction signatures/caps"
"Expect failure: Success: You cannot install a capability twice which is already in the msg sigs"
"Commit Tx 17"
```
> Change semantics of install capability

- pact-repl/Pact/Core/IR/Eval/Direct/Evaluator.hs
- pact-tests/Pact/Core/Test/StaticErrorTests.hs
- pact-tests/gas-goldens/builtinGas.golden
- pact-tests/pact-tests/runtime-tc.repl
- pact/Pact/Core/IR/Desugar.hs
- pact/Pact/Core/IR/Eval/CEK/CoreBuiltin.hs
- pact/Pact/Core/IR/Eval/CEK/Evaluator.hs
- pact/Pact/Core/IR/Eval/CEK/Types.hs
- pact/Pact/Core/Serialise/LegacyPact.hs
The pact 5 runtime TC was skipping let binds, as well as not mangling some interface names correctly which resulted in typechecking failure false positives.
PR checklist:
> Fix issues with runtime typechecker

- pact-tng.cabal
This just removes an extra dep for chainweb tests too.
> Delete lsp dep from test-utils

- pact-tests/Pact/Core/Test/ReplTests.hs
- pact-tests/pact-tests/caps.repl
- pact-tests/pact-tests/leftpad.repl
- pact-tests/pact-tests/yield.repl
- pact/Pact/Core/Builtin.hs
- pact/Pact/Core/IR/ModuleHashing.hs
- pact/Pact/Core/Serialise/CBOR_V1.hs
In pact, we rely on the repl as well as `/local` to be able to check the hash of a module before we deploy it.
When we moved to CBOR-based module hashing, I didn't notice that the CBOR instance for `ReplBuiltin` was _not_ using the enum encoding of `CoreBuiltin`. Builtins should be CBOR encoded to a simple integer,  but the repl did not match with this. 
This PR fixes this discrepancy, and it adds an extra condition to all repl tests to ensure that the module hashes of modules match in the repl vs what would be recorded on chain (as long as there are no repl natives in the module).
PR checklist:
- N/A
> Fix module hashes in repl, add test to ensure parity

- pact/Pact/Core/IR/Eval/CEK/Evaluator.hs
This ensures more robustly that all of the work done by an expression is done by the time it returns, though still some care is needed for the more nested Pact value types.
PR checklist:
> Bang-pattern on applyContToValue's value argument

- examples/accounts/accounts.pact
- pact-lsp/Pact/Core/LanguageServer/Utils.hs
- pact-repl/Pact/Core/IR/Eval/Direct/Evaluator.hs
- pact-tests/Pact/Core/Test/LexerParserTests.hs
- pact-tests/Pact/Core/Test/StaticErrorTests.hs
- pact-tests/constructor-tag-goldens/EvalError.golden
- pact/Pact/Core/Errors.hs
- pact/Pact/Core/IR/Desugar.hs
- pact/Pact/Core/IR/Eval/CEK/Evaluator.hs
- pact/Pact/Core/IR/ModuleHashing.hs
- pact/Pact/Core/IR/Term.hs
- pact/Pact/Core/Serialise/CBOR_V1.hs
- pact/Pact/Core/Serialise/LegacyPact.hs
- pact/Pact/Core/Syntax/ParseTree.hs
- pact/Pact/Core/Syntax/Parser.y
In pact 4, defpact steps have a "private entity" optional expression parameter which currently we do not support in pact 5.
Regular defpact steps take 1 argument, if they have a rollback they take 2 args.
There's an "optional" entity argument which, if present, basically causes the defpact to fail 100% of the time.
```
pact> (module m g (defcap g () true) (defpact f () (step 1 2) (step 1 2)))
"Loaded module m, hash P4sRCOphLqh1gv6h2Vw_WBVDCfRg6iDQJXLvgn0W0QY"
pact> (f)
<interactive>:0:51:Error: applyPact: step entity must be String value
at <interactive>:0:0: (f)
pact> (module m g (defcap g () true) (defpact f () (step "bob" 2) (step "bob" 2)))
"Loaded module m, hash AJ6muDjYGH0s3GOcfEso3_2wgVM45MIXknuSi9OKqpo"
pact> (f)
<interactive>:0:45:Error: applyPact: private step executed against …
```
> Fix: make entity field presence an error

- pact-lsp/Pact/Core/LanguageServer.hs
- pact-repl/Pact/Core/IR/Eval/Direct/ReplBuiltin.hs
- pact-repl/Pact/Core/Repl.hs
- pact-repl/Pact/Core/Repl/Runtime/ReplBuiltin.hs
- pact-repl/Pact/Core/Repl/Utils.hs
- pact-tests/Pact/Core/Test/GasGolden.hs
- pact-tests/Pact/Core/Test/ReplTests.hs
- pact-tests/Pact/Core/Test/StaticErrorTests.hs
- pact-tests/pact-tests/stackleak.repl
- pact/Pact/Core/Environment/Types.hs
This PR adds recording of test failures for `expect` tests in the `ReplState` that mimic's pact 4's infra.
PR checklist:
> Improve test infra for errors using expect, expect-that and expect-failure

- pact-lsp/Pact/Core/LanguageServer.hs
- pact-repl/Main.hs
- pact-repl/Pact/Core/Repl.hs
- pact-repl/Pact/Core/Repl/Utils.hs
- pact-tests/Pact/Core/Test/GasGolden.hs
- pact-tests/Pact/Core/Test/ReplTests.hs
- pact-tests/Pact/Core/Test/StaticErrorTests.hs
> exec script returns repl state

- docs/builtins/Repl/load.md
- pact-lsp/Pact/Core/LanguageServer.hs
- pact-lsp/Pact/Core/LanguageServer/Renaming.hs
- pact-lsp/Pact/Core/LanguageServer/Utils.hs
- pact-repl/Pact/Core/IR/Eval/Direct/CoreBuiltin.hs
- pact-repl/Pact/Core/IR/Eval/Direct/Evaluator.hs
- pact-repl/Pact/Core/IR/Eval/Direct/ReplBuiltin.hs
- pact-repl/Pact/Core/Repl.hs
- pact-repl/Pact/Core/Repl/Compile.hs
- pact-repl/Pact/Core/Repl/Runtime/ReplBuiltin.hs
- pact-repl/Pact/Core/Repl/UserDocs.hs
- pact-repl/Pact/Core/Repl/Utils.hs
- pact-tests/Pact/Core/Test/DocsTests.hs
- pact-tests/Pact/Core/Test/GasGolden.hs
- pact-tests/Pact/Core/Test/LegacySerialiseTests.hs
- pact-tests/Pact/Core/Test/ReplTests.hs
- pact-tests/Pact/Core/Test/StaticErrorTests.hs
- pact-tests/gas-goldens/builtinGas.golden
- pact/Pact/Core/Builtin.hs
- pact/Pact/Core/Environment/Types.hs
- pact/Pact/Core/IR/Desugar.hs
- pact/Pact/Core/Info.hs
- pact/Pact/Core/Serialise.hs
- pact/Pact/Core/Serialise/CBOR_V1.hs
- pact/Pact/Core/SizeOf.hs
- pact/Pact/Core/Syntax/ParseTree.hs
Closes #262 
Using the example in #262: 
Before this PR:
```
pact>(load "scratch/main-script.repl" true)
"Loading scratch/main-script.repl..."
"Loading nested-script.repl..."
Loaded repl defun just-fail
scratch/main-script.repl:12:2: We fail
12 | ; Hello
|   ^^^^^^^^^^^^^^^^^^^^^^^^^
at (#repl.just-fail.{I3JlcGw})
```
After this PR:
```
pact>(load "scratch/main-script.repl" true)
"Loading scratch/main-script.repl..."
"Loading nested-script.repl..."
Loaded repl defun just-fail
()
scratch/nested-script.repl:12:2: We fail
12 |   (enforce false "We fail")
|   ^^^^^^^^^^^^^^^^^^^^^^^^^
at(#repl.just-fail.{I3JlcGw}):scratch/main-script.repl 2:0-2:11
```
PR checklist:
> Fix location for span infos, report better error locations in repl

- pact/Pact/Core/Errors.hs
> Change error message for NoSuchTable

- pact-lsp/Pact/Core/LanguageServer.hs
- pact-repl/Main.hs
- pact-repl/Pact/Core/IR/Eval/Direct/ReplBuiltin.hs
- pact-repl/Pact/Core/Repl.hs
- pact-repl/Pact/Core/Repl/Compile.hs
- pact-repl/Pact/Core/Repl/Runtime/ReplBuiltin.hs
- pact-repl/Pact/Core/Repl/Utils.hs
- pact-tests/Pact/Core/Test/GasGolden.hs
- pact-tests/Pact/Core/Test/ReplTests.hs
- pact-tests/Pact/Core/Test/StaticErrorTests.hs
- pact/Pact/Core/Environment/Types.hs
Closes #261 
After this PR, the following happens on error
```
➜  pact-core git:(jose/fix-load-error-repl) cabal run pact -- scratch/261_repro.repl -t
scratch/261_repro.repl:1:1: Cannot find module:  foo
1 | (foo)
|  ^^^
Load failed
```
Moreover: Pact trace locations were not being included in `-t` output. This PR fixes that, by adding the location parameter to `replPrintLn`, but the implementor is left with the flexibility of how to actually interpret the info. This way, the repl interactive output is left untouched, but the trace output using `execScript` works as intended.
Before this PR:
```
➜  pact-core git:(jose/fix-load-error-repl) ✗ cabal run pact -- scratch/tc-fail-repro.repl -t
3
7
"Loading scratch.repl..."
"hello"
24
()
Load successful
```
After this PR
```
➜  pact-core …
```
> Fix repl load not displaying errors, return loc info to trace

- pact-repl/Pact/Core/Repl.hs
- pact-repl/Pact/Core/Repl/Compile.hs
This PR changes outputs such as 
```
Loaded imports from coin
Loaded imports from T
()
"Expect failure: Success: bad transfer-crosschain fails"
()
"Expect: success min coinbase succeeds"
"Expect failure: Success: bad coinbase fails"
()
```
Into
```
Loaded imports from coin
Loaded imports from T
"Expect failure: Success: bad transfer-crosschain fails"
"Expect: success min coinbase succeeds"
"Expect failure: Success: bad coinbase fails"
```
Suppressing the unit value from being printed to stdout. 
PR checklist:
> remove printing unit values in repl output

- .github/workflows/release-manual.yml
Per request, one could manually release without firing the brew step in the homebrew-pact repo
PR checklist:
---
- https://app.asana.com/0/0/1209274422969202
> Manual release can turn off brew

- pact-repl/Main.hs
- pact/Pact/Core/Environment/Types.hs
- pact/Pact/Core/Info.hs
```
➜  pact-core git:(jose/fix-repl-test-reporting) ✗ cabal run -O0 pact -- ../pact/blah.repl
Load successful
```
After this PR:
```
➜  pact-core git:(jose/fix-repl-test-reporting) ✗ cabal run -O0 pact -- ../pact/blah.repl
../pact/blah.repl:0:0-0:18:FAILURE: foo expected: 1, received: 2
Load failed
```
PR checklist:
- No tests for CLI output unfortunately. Maybe in the future we need some
> Pact cli now reports failures and exits on repl test failure

- pact-repl/Main.hs
- pact-repl/Pact/Core/Repl/Compile.hs
- pact-tests/Pact/Core/Test/LexerParserTests.hs
- pact-tests/Pact/Core/Test/ReplTests.hs
- pact-tests/Pact/Core/Test/StaticErrorTests.hs
- pact-tests/constructor-tag-goldens/DesugarError.golden
- pact-tests/pact-tests/meta.repl
- pact-tng.cabal
- pact/Pact/Core/Errors.hs
- pact/Pact/Core/IR/Desugar.hs
- pact/Pact/Core/NativeShadowing.hs
- pact/Pact/Core/Syntax/ParseTree.hs
- pact/Pact/Core/Syntax/Parser.y
In pact 5, we disallow natives to be shadowed. if you have an expression such as
```
(let* ((identity 1)) identity)
```
`identity` is actually resolved as the `identity` native `(lambda (x) x)`. This is actually incredibly annoying to debug because pact 4 allowed this, but we do not, since the error received is usually "Expected pact value, got closure" whenever you return a variable that collides with a native name.
This PR turns this into an error in the REPL, and we have plans to add this to mainnet on our next service release. Past a certain fork height, transactions where native names shadow variables will not make it into the mempool.
PR checklist:
> Add checks for native shadowing in REPL and shadowing check module

- pact-lsp/Pact/Core/LanguageServer.hs
- pact-repl/Pact/Core/IR/Eval/Direct/ReplBuiltin.hs
- pact-repl/Pact/Core/Repl.hs
- pact-repl/Pact/Core/Repl/Compile.hs
- pact-repl/Pact/Core/Repl/Runtime/ReplBuiltin.hs
- pact-repl/Pact/Core/Repl/Utils.hs
- pact/Pact/Core/Environment/Types.hs
For the following repl file:
```
(print "Hello Jose")
(+ 1 2)
(+ 3 4)
```
Before this PR
```
➜  pact-core git:(jose/separate-printing) pact scratch/asdf.repl 
Load successful
➜  pact-core git:(jose/separate-printing) pact scratch/asdf.repl -t
scratch/asdf.repl:0:0-0:20: "Hello Jose"
scratch/asdf.repl:1:0-1:7: 3
scratch/asdf.repl:2:0-2:7: 7
Load successful
```
After this PR:
```
➜  pact-core git:(jose/separate-printing) cabal run -O0 pact -- scratch/asdf.repl 
"Hello Jose"
Load successful
➜  pact-core git:(jose/separate-printing) cabal run -O0 pact -- scratch/asdf.repl -t
scratch/asdf.repl:0:0-0:20:Print: "Hello Jose"
scratch/asdf.repl:1:0-1:7:Trace: 3
scratch/asdf.repl:2:0-2:7:Trace: 7
Load successful
```
Closes #330 
PR checklist:
Additionally, please justify why you should or should not …
> Fix repl trace vs print

- crypto/Pact/Core/Crypto/Hash/Keccak256.hs
Support upcoming versions of the hashes package. The change is backward compatible.
> Forward compatbility for latest version of hashes

- pact-repl/Pact/Core/IR/Eval/Direct/ReplBuiltin.hs
- pact-repl/Pact/Core/Repl/Runtime/ReplBuiltin.hs
- pact-tng.cabal
- pact/Pact/Core/Version.hs
Before this PR
```
pact> (env-exec-config [])
Warning: Repl flags not recognized: 
[]
> pact --version
pact version 5.0
```
After this PR
```
pact> (env-exec-config [])
[]
> pact --version
pact version 5.2
```
PR checklist:
> fix env-exec-config emitting unknown flag warnings, bump pact version

- pact-repl/Pact/Core/Typed/Infer.hs
- pact-tests/Pact/Core/Test/TypecheckerTests.hs
- pact-tests/pact-tests/tc.repl
Fixes w-d-r so subrows typecheck correctly, example
```pact
(module test-tc-with-default-read-subrow g
(defcap g () true)
(defschema foo a:integer b:integer c:string)
(deftable footable:{foo})
(defun subrow-typechecks-default-read ()
(with-default-read footable "stuart"
{"a":1, "c":"hello"}
{"a" := a, "c" := c}
(format "there are {} of {}" [a c])
)
))
(typecheck "test-tc-with-default-read-subrow")
```
Also fixes return type bidirectionality in defuns so module references infer a bit better, so the following also typechecks
```pact
(interface foo-callable1
(defun foo-callable1:bool (s:string)))
(interface foo-callable2
(defun foo-callable2:bool (s:string)))
(module foo-callable-impl g
(defcap g () true)
(implements foo-callable1)
(implements foo-callable2)
(defun foo-callable1:bool …
```
> Fix type of with-default read in typechecker, fix defun inference to be bidirectional

- pact-lsp/Pact/Core/LanguageServer/Utils.hs
- pact-repl/Pact/Core/IR/Eval/Direct/Evaluator.hs
- pact-repl/Pact/Core/Typed/Infer.hs
- pact-tests/pact-tests/error.repl
- pact-tests/pact-tests/read-only.repl
- pact/Pact/Core/Builtin.hs
- pact/Pact/Core/IR/Desugar.hs
- pact/Pact/Core/IR/Eval/CEK/Evaluator.hs
- pact/Pact/Core/Serialise/CBOR_V1.hs
cc @CryptoPascal31
Supersedes #273 (Saves me a rebase).
[Implements KIP 0024](https://github.com/kadena-io/KIPs/pull/53). 
This PR adds two special forms into pact. 
`(pure k)` for some expression `k` will evaluate `k` in read-only mode. That is, the evaluation of `k` cannot write to the database, only read. 
[Example here](https://github.com/kadena-io/pact-5/blob/63c0aa53ecbd1652d43bb208bd672bb3ee817814/pact-tests/pact-tests/read-only.repl)
```
Γ ⊢ e : t
───────────────  (pure)
Γ ⊢ (pure e) : t
```
`pure` has been a community ask for a while, and allows users to use the power of `try` but without forcing users to write `(try (enforce false "boom") something)
`(error foo)` for some string valued expression `foo` (e.g `"hello"` or `(format "{}" ["bar"])`) will throw a recoverable error (so …
> "pure" and "error" special forms

- pact-repl/Pact/Core/IR/Eval/Direct/Evaluator.hs
- pact-tests/pact-tests/caps.repl
- pact/Pact/Core/IR/Eval/CEK/Evaluator.hs
cc @CryptoPascal31
[Implements KIP 0027](https://github.com/kadena-io/KIPs/pull/56), and loosens the restriction that `enforce` should be sys-only as well. This was probably the for FV's sake, but considering we need to revamp FV as well, I think it makes sense to loosen this restriction.
It also adds regression tests for this behaviour as well.
As a bit of historical background note: pact did not used to always have runtime recursion checking, but now that we do, I think it's probably fair to consider this as a straight enhancement. We are still not vulnerable to any sort of reentrant attacks due to the mode being set to read-only.
PR checklist:
> Enforce and user guards as read-only

- docs/builtins/Repl/typecheck.md
> typecheck: Minor doc updates for consistency with other functions

- docs/builtins/Repl/env-sigs.md
> Expanded example for env-sigs

- pact-repl/Pact/Core/IR/Eval/Direct/Evaluator.hs
- pact-repl/Pact/Core/IR/Eval/Direct/Types.hs
- pact-tests/pact-tests/reentrancy.repl
- pact/Pact/Core/Environment/Types.hs
- pact/Pact/Core/IR/Eval/CEK/Evaluator.hs
- pact/Pact/Core/IR/Eval/CEK/Types.hs
Similar to #362 , but without a special form.
It turns all module reference calls back into the calling module into read-only. That is, any function call via module references that calls back into the calling module itself will call any function in the calling module in read-only mode (So no DB modifications are possible).
See the test: Stub
An inline example:
For some interface
```pact
(interface some-interface
(defun some-function:integer (param:integer))
```
and some caller:
```pact
(module some-module GOV
(defcap GOV () (error "non-upgradable") ; Pact 5.3 feature on master, (error "foo") same as (enforce false "foo") but with different type
...
(defun vulnerable-function (m:module{some-interface})
(with-capability (SENSITIVE-CAP)
(m::some-function 42))))
(defun …
```
> [Experimental] Add read-only reentrancy guarding for all modref calls
