kadena-io/pact-5

pact-lsp/Pact/Core/LanguageServer.hs
pact-lsp/Pact/Core/LanguageServer/Utils.hs
pact-tests/Pact/Core/Test/LanguageServer.hs
pact-tests/Pact/Core/Test/PersistenceTests.hs
pact-tests/Pact/Core/Test/ReplTests.hs
pact-tests/Pact/Core/Test/StaticErrorTests.hs
pact-tests/pact-tests-lsp/builtin-overloads-hover.repl
pact/Pact/Core/Builtin.hs
pact/Pact/Core/Repl.hs
pact/Pact/Core/Repl/Compile.hs
repl/Main.hs

closes #78 
This PR also fixes same missing AST traversals resulting in bad position matching.
PR checklist:
---
- https://app.asana.com/0/0/1206473309875668
- https://app.asana.com/0/0/1206417680988244

fix repl completion of repl natives

---

README.md

Update New Kadena Logo in README.md

---

pact-tests/pact-tests/parsing.repl
pact/Pact/Core/Builtin.hs
pact/Pact/Core/Gas/TableGasModel.hs
pact/Pact/Core/IR/Desugar.hs
pact/Pact/Core/IR/Eval/CoreBuiltin.hs
pact/Pact/Core/Serialise/CBOR_V1.hs

closes #77
PR checklist:
---
- https://app.asana.com/0/0/1206473309875661

add `cond` builtin

---

pact-lsp/Pact/Core/LanguageServer.hs

LSP sync options, debug information

---

pact/Pact/Core/IR/Eval/CEK.hs

Add some documentation to resume pact.
PR checklist:

add resume defpact documentation

---

flake.lock
flake.nix

update ghc to 9.6.4

---

pact-lsp/Pact/Core/LanguageServer.hs
pact-tests/Pact/Core/Test/PersistenceTests.hs
pact-tests/Pact/Core/Test/ReplTests.hs
pact-tests/Pact/Core/Test/StaticErrorTests.hs
pact-tests/pact-tests/db.repl
pact-tests/pact-tests/toplevel.repl
pact/Pact/Core/Builtin.hs
pact/Pact/Core/IR/Term.hs
pact/Pact/Core/Repl.hs
pact/Pact/Core/Repl/Compile.hs
pact/Pact/Core/Repl/Runtime/ReplBuiltin.hs
pact/Pact/Core/Repl/Utils.hs

env-enable-repl-natives

---

gasmodel/Pact/Core/GasModel/InterpreterGas.hs

As discussed with @jmcardon , it actually makes more sense to just leave the evaluation state out when normalizing the evaluation result, and only consider the actual result itself.
PR checklist:

Don't `nf` the eval state in benchmarks

---

gasmodel/Main.hs
gasmodel/Pact/Core/GasModel/BuiltinsGas.hs
gasmodel/Pact/Core/GasModel/InterpreterGas.hs
gasmodel/Pact/Core/GasModel/Utils.hs
pact-tests/Pact/Core/Test/StaticErrorTests.hs
pact/Pact/Core/Environment/Types.hs
pact/Pact/Core/Gas.hs
pact/Pact/Core/Gas/TableGasModel.hs
pact/Pact/Core/IR/Eval/CEK.hs
pact/Pact/Core/IR/Eval/CoreBuiltin.hs
pact/Pact/Core/IR/Eval/Runtime/Utils.hs
pact/Pact/Core/Repl/Runtime/ReplBuiltin.hs

Gas model tweaks

---

gasmodel/Pact/Core/GasModel/InterpreterGas.hs
gasmodel/Pact/Core/GasModel/Utils.hs
pact-tests/legacy-serial-tests/coin-v5/coin-v5.repl
pact-tests/pact-tests/caps.repl
pact-tests/pact-tests/coin-v1.repl
pact-tests/pact-tests/coin-v5.repl
pact-tests/pact-tests/verifiers.repl
pact-tng.cabal
pact/Pact/Core/Builtin.hs
pact/Pact/Core/Capabilities.hs
pact/Pact/Core/Environment/Types.hs
pact/Pact/Core/Environment/Utils.hs
pact/Pact/Core/Evaluate.hs
pact/Pact/Core/Gas/TableGasModel.hs
pact/Pact/Core/IR/Eval/CEK.hs
pact/Pact/Core/IR/Eval/CoreBuiltin.hs
pact/Pact/Core/IR/Eval/Runtime/Types.hs
pact/Pact/Core/Repl/Runtime/ReplBuiltin.hs
pact/Pact/Core/Serialise/CBOR_V1.hs
pact/Pact/Core/Syntax/Lexer.x
pact/Pact/Core/Verifiers.hs

Implement Verifiers

---

pact/Pact/Core/Errors.hs
pact/Pact/Core/Evaluate.hs
pact/Pact/Core/IR/Eval/CEK.hs
pact/Pact/Core/SPV.hs
pact/Pact/Core/Serialise/LegacyPact.hs

New stuff for the chainweb integration

---

pact/Pact/Core/Persistence/SQLite.hs

PR checklist:
---
- https://app.asana.com/0/0/1206187105047164

SQLite Statement caching

---

pact-lsp/Pact/Core/LanguageServer.hs
pact-tests/Pact/Core/Test/LanguageServer.hs
pact-tests/pact-tests-lsp/dependency-load.repl
pact-tests/pact-tests-lsp/jump-to-definition-other-file.repl

This PR adds support for working with multiple files.
PR checklist:
---
- https://app.asana.com/0/0/1207671608986276

add multi-file lsp support

---

docs/builtins/Database/describe-keyset.md
docs/builtins/Repl/begin-tx.md
docs/builtins/Repl/continue-pact.md
docs/builtins/Repl/env-events.md
docs/builtins/Repl/env-hash.md
docs/builtins/Repl/env-keys.md
docs/builtins/Repl/expect-failure.md

@sstraatemans @lsgunnlsgunn please see this PR, it corrects the heading level for a correct visualization
PR checklist:
---
- https://app.asana.com/0/0/1207708004475408

correct heading of docs

---

.github/workflows/nix.yml
cabal.project
flake.lock
flake.nix
pact-tests/Pact/Core/Test/LanguageServer.hs
pact-tng.cabal

add hackage input. make it updateable from this repo.

---

cabal.project
pact-tests/Pact/Core/Test/LanguageServer.hs

remove aeson < 2.2 constrain

---

gasmodel/Pact/Core/GasModel/ContractBench.hs
pact/Pact/Core/Environment/Utils.hs
pact/Pact/Core/Evaluate.hs
pact/Pact/Core/IR/Eval/CEK.hs
pact/Pact/Core/IR/Eval/CEK/Types.hs
pact/Pact/Core/Info.hs
pact/Pact/Core/Interpreter.hs
pact/Pact/Core/Repl/Compile.hs
pact/Pact/Core/StackFrame.hs

Info alias, Evaluate fixes

---

pact/Pact/Core/Errors.hs

Add UnknownException error case

---

pact/Pact/Core/Environment/Types.hs
pact/Pact/Core/IR/Desugar.hs
pact/Pact/Core/Syntax/LexUtils.hs

Use deriving newtype when possible

---

pact-request-api/Pact/Core/Command/Types.hs

Add unsafeParseCommand

---

pact-tng.cabal

make pact-request-api publicly visible

---

pact-tests/Pact/Core/Test/LexerParserTests.hs
pact-tests/Pact/Core/Test/PersistenceTests.hs
pact-tests/Pact/Core/Test/SerialiseTests.hs
pact-tng.cabal
test-utils/Pact/Core/Gen.hs

Split Pact.Core.Gen out of test suite into its own library for

---

pact/Pact/Core/Persistence/Types.hs

Add instance Show (Domain k v b i)

---

test-utils/Pact/Core/Gen.hs

Use Gen.recursive and hedgehog size param in Gens

---

pact/Pact/Core/Names.hs

Add instance IsString Field

---

cabal.project
crypto/Pact/Core/Crypto/Hash/Poseidon.hs
crypto/Pact/Core/Crypto/Pairing.hs
flake.lock
flake.nix
gasmodel/Pact/Core/GasModel/BuiltinsGas.hs
pact-request-api/Pact/Core/Command/Client.hs
pact-tests/Pact/Core/Test/PersistenceTests.hs
pact-tests/Pact/Core/Test/SizeOfTests.hs
pact-tests/Pact/Core/Test/ZkTests.hs
pact-tng.cabal
pact/Pact/Core/DeriveConTag.hs
pact/Pact/Core/IR/Desugar.hs
pact/Pact/Core/IR/Eval/CEK.hs
pact/Pact/Core/Literal.hs
pact/Pact/Core/Serialise/LegacyPact.hs
pact/Pact/Core/SizeOf.hs
unsafe/src/Data/Foldable/Unsafe.hs
unsafe/src/Data/List/Unsafe.hs

PR checklist:
---
- https://app.asana.com/0/0/1207784560848157

make pact compile with ghc 9.10

---

pact/Pact/Core/Gas/Types.hs
pact/Pact/Core/PactValue.hs
pact/Pact/Core/Persistence/Types.hs

some extra prisms

---

pact/Pact/Core/Evaluate.hs

Derive Functor for EvalResult

---

pact/Pact/Core/Evaluate.hs

set up EvalEnv and EvalState within eval functions

---

pact-tests/Pact/Core/Test/SerialiseTests.hs
pact/Pact/Core/Guards.hs
pact/Pact/Core/Names.hs
pact/Pact/Core/Serialise/CBOR_V1.hs
pact/Pact/Core/Serialise/LegacyPact/Types.hs

This PR now removes all orphan instances replaced with newtypes
Blocked on #185 
PR checklist:

Remove all orphan instances

---

pact-request-api/Pact/Core/Command/Client.hs
pact-request-api/Pact/Core/Command/RPC.hs
pact-tests/Pact/Core/Test/CommandTests.hs
pact-tests/Pact/Core/Test/SignatureSchemeTests.hs
pact/Pact/Core/StableEncoding.hs

Use PactValue for data field

---

pact-request-api/Pact/Core/Command/Types.hs
pact/Pact/Core/Evaluate.hs
pact/Pact/Core/StableEncoding.hs

Changes in this PR are purely for chainweb's API and thus do not impact pact's test suite.
Test Coverage is done on chainweb directly.
PR checklist:

Add Necessary encodings for Local, Add ExecutionMode to the Evaluate API

---

pact-request-api/Pact/Core/Command/RPC.hs

add lenses and prisms for Command RPC types

---

pact/Pact/Core/Persistence/Types.hs

add hashTxLogs

---

pact/Pact/Core/Persistence/Types.hs

fix hashTxLogs

---

pact-tng.cabal

add lower bound for lsp-test

---

.github/workflows/release-manual.yml
.github/workflows/release-nightly.yml

Fixing release scripts

---

docs/builtins/General/acquire-module-admin.md

fix acquire-module-admin docs

---

pact/Pact/Core/StableEncoding.hs

Encode PactValue Unit as json null

---

pact-request-api/Pact/Core/Command/RPC.hs

strictify ExecMsg fields

---

pact/Pact/Core/StableEncoding.hs

add eitherDecodeStable

---

pact/Pact/Core/Errors.hs
pact/Pact/Core/Evaluate.hs

This way chainweb can at least print these errors, though we will never put them on-chain.
PR checklist:

Add exception parameter to UnknownException

---

pact/Pact/Core/Errors.hs

Fix mispelled accessor

---

bench/Bench.hs

fix bench compilation

---

docs/builtins/Database/describe-module.md
docs/builtins/Database/list-modules.md
pact-tests/constructor-tag-goldens/CoreBuiltin.golden
pact-tests/gas-goldens/builtinGas.golden
pact-tests/gas-goldens/list-modules.repl
pact/Pact/Core/Builtin.hs
pact/Pact/Core/Gas/TableGasModel.hs
pact/Pact/Core/IR/Eval/CEK/CoreBuiltin.hs
pact/Pact/Core/IR/Eval/Direct/CoreBuiltin.hs

Reintro `list-modules`, ensuring it's local-only

---

pact-request-api/Pact/Core/Command/Server.hs
pact-tests/Pact/Core/Test/PactServerTests.hs
pact-tests/Pact/Core/Test/ServerUtils.hs

fix pact-server

---

gasmodel/Pact/Core/GasModel/BuiltinsGas.hs
gasmodel/Pact/Core/GasModel/ContractBench.hs
gasmodel/Pact/Core/GasModel/Utils.hs
pact-request-api/Pact/Core/Command/Client.hs
pact-request-api/Pact/Core/Command/Server.hs
pact-request-api/Pact/Core/Command/SigData.hs
pact-request-api/Pact/Core/Command/Types.hs
pact-tests/Pact/Core/Test/ClientTests.hs
pact-tests/Pact/Core/Test/JSONRoundtripTests.hs
pact-tests/Pact/Core/Test/PactContinuationTest.hs
pact-tests/Pact/Core/Test/PactServerTests.hs
pact-tests/Pact/Core/Test/PersistenceTests.hs
pact-tests/Pact/Core/Test/SerialiseTests.hs
pact-tests/Pact/Core/Test/ServerUtils.hs
pact/Pact/Core/Compile.hs
pact/Pact/Core/Errors.hs
pact/Pact/Core/Evaluate.hs
pact/Pact/Core/Info.hs
pact/Pact/Core/Serialise.hs
pact/Pact/Core/Serialise/CBOR_V1.hs
pact/Pact/Core/SizeOf.hs
profile-tx/ProfileTx.hs
test-utils/Pact/Core/Gen.hs
test-utils/Pact/Core/PactDbRegression.hs

Add Located Error Info

---

pact-request-api/Pact/Core/Command/History.hs
pact-request-api/Pact/Core/Command/Server.hs
pact-request-api/Pact/Core/Command/Server/History.hs
pact-tests/Pact/Core/Test/PactServerTests.hs
pact-tests/Pact/Core/Test/ServerUtils.hs
pact-tng.cabal

add pact-server history

---

pact/Pact/Core/Capabilities.hs
pact/Pact/Core/Info.hs

add ord instance for pactevent

---

pact-tests/pact-tests/format-regression.repl
pact/Pact/Core/Guards.hs
pact/Pact/Core/IR/Eval/Runtime/Utils.hs
pact/Pact/Core/PactValue.hs

add pactValueToText

---

pact/Pact/Core/Errors.hs

Eval errors

---

pact/Pact/Core/Errors.hs

hyperlane error punctation

---

pact-tests/Pact/Core/Test/PactContinuationTest.hs
pact-tests/pact-tests/object-evaluation-order-regression.repl
pact/Pact/Core/Syntax/Parser.y

correct object evaluation order, closes #260

---

pact/Pact/Core/Errors.hs

DB error messages

---

docs/builtins/General/acquire-module-admin.md
docs/builtins/General/static-redeploy.md
gasmodel/Pact/Core/GasModel/BuiltinsGas.hs
pact-lsp/Pact/Core/LanguageServer.hs
pact-tests/constructor-tag-goldens/CoreBuiltin.golden
pact-tests/gas-goldens/builtinGas.golden
pact-tests/gas-goldens/static-redeploy.repl
pact-tests/legacy-serial-tests/coin-v5/coin-v5.repl
pact-tests/pact-tests/coin-v1.repl
pact-tests/pact-tests/coin-v5.repl
pact-tests/pact-tests/static-redeploy.repl
pact/Pact/Core/Builtin.hs
pact/Pact/Core/Compile.hs
pact/Pact/Core/Evaluate.hs
pact/Pact/Core/Gas/TableGasModel.hs
pact/Pact/Core/Gas/Types.hs
pact/Pact/Core/IR/Eval/CEK/CoreBuiltin.hs
pact/Pact/Core/IR/Eval/Direct/CoreBuiltin.hs
pact/Pact/Core/IR/ModuleHashing.hs

Add static redeploy native

---

pact-tests/pact-tests/caps.repl
pact/Pact/Core/Errors.hs

user errors

---

pact/Pact/Core/Syntax/LexUtils.hs
pact/Pact/Core/Syntax/Parser.y

fix happy error after pump

---

docs/builtins/Database/fold-db.md
docs/builtins/Database/txlog.md
docs/builtins/Database/write.md

Add more information to the write function and update syntax case

---

pact-tests/Pact/Core/Test/StaticErrorTests.hs
pact/Pact/Core/IR/Desugar.hs
pact/Pact/Core/IR/Eval/CEK/CoreBuiltin.hs
pact/Pact/Core/IR/Eval/CEK/Evaluator.hs
pact/Pact/Core/Serialise/LegacyPact.hs

fix bug with inlined deftable in legacy serialization

---

pact/Pact/Core/Errors.hs

Make PactErrorCompat prisms

---

pact-tng.cabal

Expose pact-repl

---

docs/builtins/General/describe-namespace.md
docs/builtins/General/namespace.md
docs/builtins/Guards/create-principal.md
docs/builtins/Repl/env-keys.md
docs/builtins/SPV/verify-spv.md
docs/builtins/Time/format-time.md
docs/builtins/Time/hours.md
docs/builtins/Time/minutes.md
docs/builtins/Time/parse-time.md

Changes to pact functions for the new docs site

---

pact/Pact/Core/Guards.hs
pact/Pact/Core/Hash.hs
pact/Pact/Core/Names.hs

Add Hashable instances for table keys

---

pact-repl/Main.hs
pact-request-api/Pact/Core/Command/Server.hs
pact-request-api/Pact/Core/Command/Server/History.hs
pact-tests/Pact/Core/Test/ClientTests.hs
pact-tests/Pact/Core/Test/JSONRoundtripTests.hs
pact-tests/Pact/Core/Test/PactContinuationTest.hs
pact-tests/PactCoreTests.hs
pact/Pact/Core/Errors.hs
pact/Pact/Core/Names.hs
pact/Pact/Core/SatWord.hs
test-utils/Pact/Core/Gen.hs

Revamp error codes to have the same format as legacy errors

---

pact/Pact/Core/Errors.hs

add fallback case in pactonchainerror codec

---

pact-tests/Pact/Core/Test/ClientTests.hs
pact-tests/Pact/Core/Test/PactContinuationTest.hs
pact/Pact/Core/Errors.hs

change error types to be compatible with pact 4

---

.github/CODEOWNERS

This change is mostly reflecting the actual code+review contribution of this repo.

Change codeowners to Jose + Robert

---

docs/builtins/Repl/load.md

Clean up and correct the load function example text

---

docs/builtins/General/cond.md
docs/builtins/General/do.md
docs/builtins/General/negate.md
docs/builtins/General/show.md
docs/builtins/Repl/env-milligas.md
docs/builtins/Repl/env-module-admin.md
docs/builtins/Repl/env-set-debug-flag.md
docs/builtins/Repl/env-set-milligas.md
docs/builtins/Repl/env-verifiers.md
docs/builtins/Repl/pact-state.md
docs/builtins/Repl/print.md
docs/builtins/Repl/rollback-tx.md
docs/builtins/Repl/sig-keyset.md
docs/builtins/Repl/test-capability.md
pact-repl/Pact/Core/IR/Eval/Direct/ReplBuiltin.hs
pact-repl/Pact/Core/Repl.hs
pact-repl/Pact/Core/Repl/BuiltinDocs.hs
pact-repl/Pact/Core/Repl/BuiltinDocs/Internal.hs
pact-repl/Pact/Core/Repl/Compile.hs
pact-repl/Pact/Core/Repl/Runtime/ReplBuiltin.hs
pact-tests/Pact/Core/Test/DocsTests.hs
pact-tng.cabal
pact/Pact/Core/Builtin.hs
pact/Pact/Core/IR/Desugar.hs

Add multi-line detection for unclosed parens, add docs for missing natives, add test for pandoc roundtripping
Closes #302 
PR checklist:

Separate pandoc rendering and scope it to repl only.

---

pact-tests/Pact/Core/Test/Keccak256Tests.hs
pact-tests/PactCoreTests.hs
pact-tng.cabal
pact/Pact/Core/Environment/Utils.hs

add tests for keccak256

---

CHANGELOG.md

Release pact 5.1

---

pact/Pact/Core/Compile.hs

Fix ordering of writes broken by transitive deps PR

---

pact-request-api/Pact/Core/Command/Server.hs
pact/Pact/Core/Persistence/SQLite.hs

Fix local in pact server

---

pact/Pact/Core/StableEncoding.hs

Add _StableEncoding iso

---

pact/Pact/Core/Persistence/Types.hs

Change-Id: Id0000000c7e18778beb28d62c78e1436444ef4c3
PR checklist:

Add new NFData instance for TxLog

---

pact/Pact/Core/Gas/Types.hs

Add _Gas prism

---

pact-repl/Pact/Core/IR/Eval/Direct/CoreBuiltin.hs
pact-repl/Pact/Core/IR/Eval/Direct/Evaluator.hs
pact-tests/Pact/Core/Test/StaticErrorTests.hs
pact-tests/pact-tests/caps.repl
pact-tests/pact-tests/keysets.repl
pact-tng.cabal
pact/Pact/Core/Capabilities.hs
pact/Pact/Core/Compile.hs
pact/Pact/Core/Environment/Types.hs
pact/Pact/Core/IR/Eval/CEK/CoreBuiltin.hs
pact/Pact/Core/IR/Eval/CEK/Evaluator.hs
pact/Pact/Core/IR/Eval/Runtime/Utils.hs
pact/Pact/Core/Names.hs
pact/Pact/Core/Version.hs
unsafe/src/Data/List/Unsafe.hs

Add magic caps for auth natives, bump pact version

---

pact-repl/Pact/Core/Typed/Infer.hs
pact/Pact/Core/IR/Desugar.hs

Improve typechecker errors

---

docs/builtins/General/do.md
docs/builtins/Repl/print.md

do, print: Clarify examples

---

docs/builtins/Repl/expect-that.md

Fix typo in examples section

---

docs/builtins/General/enforce-verifier.md

Suggested improvements from Jermaine.
PR checklist:
---
- https://app.asana.com/0/0/1210876821915459

Add better example and xref to enforce-verifiers

---

docs/builtins/Database/list-modules.md
docs/builtins/General/list-module.md

Seems like it might be local only in two places
